### ISSUE TITLE
No se generan en las trazas xAPI las trazas skipped video

### ISSUE THREAD

**Issue by jujusb** [e-ucm/uAdventure#104]
Hola, en las trazas xAPI del FirstAid no se generan las trazas de skipped de los videos,  sabrias porqué no se generan ?
En la primera versión de First Aid que tenía se generaban las trazas skipped y ahora probando con la traducción no no generan las trazas skipped.

**Comment by Victorma** [comment]
Closed in https://github.com/e-ucm/uAdventure/commit/0637beacfedb6a4a96a7b464b3457129c790338f
