### ISSUE TITLE
Problema con codificación de los variables de localización de los objetos.

### ISSUE THREAD

**Issue by LiyliLee** [e-ucm/uAdventure#131]
Sigo sin funcionando los localizaciones de los objetos en el release v.1.1.3, no me deja abrir correctamente el GeoMapa y todos los GeoElements.

**Comment by Victorma** [comment]
Fixed in https://github.com/e-ucm/uAdventure/commit/c25c33857970af7868cfbddb1efb25c84bcd2acf
