### ISSUE TITLE
Eliminar un elemento de la tabla de contenidos de un geo-elemento da error

### ISSUE THREAD

**Issue by georgimednikov** [e-ucm/uAdventure#132]
El error ocurre cuando se selecciona un geo-elemento desde una Map Scene.

![image](https://user-images.githubusercontent.com/48915821/103460892-5c6bf700-4d1a-11eb-96ca-174cfd0403b2.png)
En la foto de arriba si se elimina el elemento 2 la interfaz acabará como la imagen de abajo dando un error de Index out of range

![image](https://user-images.githubusercontent.com/48915821/103460909-8de4c280-4d1a-11eb-9991-15ee368d8fcc.png)

Espero haberlo explicado bien.

**Comment by mmur07** [comment]
También sucede cuando eliminas uno de los varios miembros de un geo-element.

![image](https://user-images.githubusercontent.com/47757791/103461084-c9cc5780-4d1b-11eb-91fd-c69feab7a0e4.png)

Al eliminarlo devuelve un error y sucede esto:

![image](https://user-images.githubusercontent.com/47757791/103461097-f2545180-4d1b-11eb-955d-ceb97e08f7da.png)

**Comment by Victorma** [comment]
Entiendo que lo que causa error borrar es múltiples geometrías, así que voy a intentar corregirlo para la próxima versión.
