### ISSUE TITLE
Poder crear bloques de condiciones para utilizarlos en varios sitios

### ISSUE THREAD

**Issue by apoyatos** [e-ucm/uAdventure#135]
Para facilitar la creación y modificación de condiciones y evitar tener que repetir su creación cuando se quiera aplicar a un nuevo objeto. El desarrollador podría definir un bloque de condiciones y mas tarde referenciarlo en uno o varios lugares

**Comment by Victorma** [comment]
Esto ya existe, se llaman GlobalStates y están en la sección avanzada

**Comment by Victorma** [comment]
De una manera análoga también existen las macros que son algo así como efectos que pueden lanzarse de forma global dentro de otros efectos, así como si fueran funciones globales.
