### ISSUE TITLE
Error creating set of slidescenes

### ISSUE THREAD

**Issue by icelor01** [e-ucm/uAdventure#14]
Hello, I have some errors when trying to create a set of slides of the slidescene. I send attached the console log. Thanks in advance.
![ua_issue-problem creating set of slidescenes](https://user-images.githubusercontent.com/44441091/47738085-a9536f00-dc72-11e8-9ec2-91708349189c.png)

**Comment by Victorma** [comment]
Hi! What version of Unity are you using?

**Comment by icelor01** [comment]
Hi! 2017.3.1f1, Maybe it works with 2018.2.14 release?

**Comment by Victorma** [comment]
I'll take a look to this and see whats going on. What could be useful too is that you upload here your Unity project just in case.
Are you working with the release or with a clone?

**Comment by icelor01** [comment]
Sorry Victor, for replying so late.
I was working with uAdventure release, although I am not sure what do you mean with a clone.
I was following the user guide of uAdventure when I had this problem. Thank you in advance.

**Comment by Victorma** [comment]
I'm pretty sure you won't have this issue anymore, so don't worry. If you experience it again, just post it here and I'll solve it.

Thank you!
