### ISSUE TITLE
Milestone controller error

### ISSUE THREAD

**Issue by MiguelMulas** [e-ucm/uAdventure#32]
![image](https://user-images.githubusercontent.com/18732385/53968935-33678480-40f8-11e9-86ae-cf5de5cbed6c.png)
[CurrentGame.zip](https://github.com/e-ucm/uAdventure/files/2942047/CurrentGame.zip)

**Comment by Victorma** [comment]
The issue happens when an ActiveArea is used.
Since ActiveAreas are not representables the game crashes.
Now InteractiveElement is used instead
