### ISSUE TITLE
The character looks "Right" by default, but should look "Down"

### ISSUE THREAD

**Issue by alex97ortega** [e-ucm/uAdventure#34]
The characters in the scene look *Right* by default, but they should look *Down* as the most important look

**Comment by Victorma** [comment]
I have to check how this feature was implemented originally in the eAdventure editor and I will make sure it has been implemented the same way in uAdventure.

**Comment by Victorma** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [uAdventure v0.12](https://trello.com/c/nvkCa2gk/127-uadventure-v012)
