### ISSUE TITLE
The player disapears when hit play if the player's scale is < 1

### ISSUE THREAD

**Issue by borjacano97** [e-ucm/uAdventure#36]
The problem seems to be that if the player scale is lees that 1, the player scale goes huge for no reason and cannot be renderered.

![image](https://user-images.githubusercontent.com/19183801/54372761-4e983e00-467c-11e9-8daa-8acf0ad7f077.png)
*Scale < 1*

![image](https://user-images.githubusercontent.com/19183801/54372781-59eb6980-467c-11e9-8ae2-78484dfb1206.png)

![image](https://user-images.githubusercontent.com/19183801/54372793-62dc3b00-467c-11e9-9cae-a5a31c4f73f3.png)
*Not rendered*
![image](https://user-images.githubusercontent.com/19183801/54372821-71c2ed80-467c-11e9-8653-3e73d639986a.png)
*The scale goes huge*

**Comment by Victorma** [comment]
Can you please upload a compressed (preferred zip) copy of your CurrentGame folder?

**Comment by Victorma** [comment]
Please dont forget to upload your currentgame folder.

**Comment by Victorma** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [uAdventure v0.12](https://trello.com/c/nvkCa2gk/127-uadventure-v012)

**Comment by borjacano97** [comment]
Cannot upload the current game folder because we ditched it and started a new project. Sorry ^^'
