### ISSUE TITLE
Error efectos en ítem (mostar texto)

### ISSUE THREAD

**Issue by adralcan** [e-ucm/uAdventure#41]
Creando un efecto a un ítem se ha desplazado fuera de la ventana al minimizarlo después de editarlo.

![image](https://user-images.githubusercontent.com/3171485/54631271-f1d1c480-4a7b-11e9-9011-eec9797a6808.png)

**Comment by Victorma** [comment]
A quick fix to this would be to save the project, play/stop the game to force a reload, and reopen the effects. The'll be repositioned automatically.

Even so, this is probably a bug as this window has never been minimized before.

**Comment by Victorma** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [uAdventure v0.12](https://trello.com/c/nvkCa2gk/127-uadventure-v012)

**Comment by Victorma** [comment]
He arreglado esto, pero el bug que ha causado que se fuera de madre no sé cual puede ser. Si eres capaz de replicarlo genial, pero ahora como máximo se te irá al borde de la pantalla.
