### ISSUE TITLE
See blocking conditions hovering the mouse above the red lock

### ISSUE THREAD

**Issue by daquinte** [e-ucm/uAdventure#44]
![HoverInfo](https://user-images.githubusercontent.com/18736531/54694599-be00a880-4b28-11e9-94ee-36042ea23eef.png)

Just a suggestion, I would love to see the conditions that lock a certain option hovering above the red lock or something like that. The pop-up window when you click is nice if you only have a few, but as the project grows it becomes tedious to check one by one for the conditions involved in every option/dialogue.

**Comment by Victorma** [comment]
Interesting feature!

I was thinking into making the conditions window appear as a dropdown instead of a popup, which would solve the problem too and make it more usable.

What do you think would be a better approach. Both could be a solution too.

**Comment by daquinte** [comment]
Now that you mention it, I would go with the dropdown instead of the pop-up because my approach only works if you have a few conditions. However, if you have several of them, hovering accidentally would be distracting and annoying. The dropdown will work better if you have several conditions, but I would make it that it only deploys if clicked.
