### ISSUE TITLE
Texto de color prácticamente igual al del fondo

### ISSUE THREAD

**Issue by adralcan** [e-ucm/uAdventure#55]
EL texto de las propiedades es del mismo color que el fondo y no se aprecia bien. 
Relacionado con este issue en el mismo popup, cuando añadimos una acción personalizada el cuadro de las acciones se reduce a un tamaño en el que solo se ve una acción disponible.

**Comment by Victorma** [comment]
Posiblemente se deba al uso de la Skin pro de Unity
