### ISSUE TITLE
Problemas guardado de objetos

### ISSUE THREAD

**Issue by mjcguada** [e-ucm/uAdventure#59]
Cuando editas un objeto desde la pestaña items y pulsas play, no aparece el recordatorio de guardar cambios antes de ejecutar, y estos se descartan.

**Comment by Victorma** [comment]
En general, cambiar cualquier imagen no muestran el recordatorio

**Comment by Synpheros** [comment]
Estaba pensando que, quizás sea una buena idea persistir todos los cambios siempre en una versión "dirty" de los descriptores en un "_chapter1.xml" para que aunque se cierre el editor o te olvides de guardar, siempre tire de ahí y no pierdas cambios.

**Comment by Victorma** [comment]
Merged to #21
