### ISSUE TITLE
La pestaña Analytics genera una cantidad ingente de errores y no permite trabajar con ella

### ISSUE THREAD

**Issue by borjacano97** [e-ucm/uAdventure#61]
A ver, este es una de los gordos.
Cuando nos metemos a la pestaña de Analytics todo parece bien, pero cuando se empiezan a desplegar los menús desplegables al añadir un `Completable`  deja de actualizarse las opciones, indistintamente del valor que elijas no se actualiza.
![image](https://user-images.githubusercontent.com/19183801/54844558-7ff5b700-4cd7-11e9-9baa-f68cca934ca7.png)
![image](https://user-images.githubusercontent.com/19183801/54844602-926ff080-4cd7-11e9-992b-19def772291e.png)

 Eso genera una cantidad desmedida de errores en el GUI 
![image](https://user-images.githubusercontent.com/19183801/54844482-5472cc80-4cd7-11e9-8ec6-20b9a573fe6a.png)
![image](https://user-images.githubusercontent.com/19183801/54844504-5f2d6180-4cd7-11e9-98c8-18518649e7d4.png)

Adjunto aquí el log de los errores
- Error 1:
```
ArgumentException: method return type is incompatible
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, Boolean throwOnBindFailure) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Delegate.cs:190)
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Delegate.cs:276)
uAdventure.Editor.ChangeValueTool`2[O,T].Init (.O data, .T newValue, System.Reflection.MethodInfo getter, System.Reflection.MethodInfo setter, Boolean updateTree, Boolean updatePanel)
uAdventure.Editor.ChangeValueTool`2[O,T]..ctor (.O data, .T newValue, System.String getMethodName, System.String setMethodName, Boolean updateTree, Boolean updatePanel)
uAdventure.Editor.ChangeValueTool`2[O,T]..ctor (.O data, .T newValue, System.String getMethodName, System.String setMethodName)
uAdventure.Editor.ChangeEnumValueTool..ctor (System.Object data, System.Enum newValue, System.String getMethodName, System.String setMethodName)
uAdventure.Editor.ScoreDataControl.setType (ScoreType scoreType)
uAdventure.Editor.CompletablesWindow.ScoreEditor (Rect rect, uAdventure.Editor.ScoreDataControl score)
uAdventure.Editor.CompletablesWindow.<.ctor>b__10_0 (Rect rect, Int32 row, Int32 column, Boolean isActive, Boolean isFocused)
uAdventure.Editor.ColumnList+<>c__DisplayClass20_0.<Init>b__2 (Rect columnRect, Int32 column)
uAdventure.Editor.ColumnList.drawColumns (Rect rowRect, System.Action`2 callback)
uAdventure.Editor.ColumnList.<Init>b__20_1 (Rect rect, Int32 index, Boolean isActive, Boolean isFocused)
ScrollableList.OnElementCallback (Rect rect, Int32 index, Boolean isActive, Boolean isFocused)
UnityEditorInternal.ReorderableList.DoListElements (Rect listRect) (at C:/buildslave/unity/build/Editor/Mono/GUI/ReorderableList.cs:587)
UnityEditorInternal.ReorderableList.DoList (Rect rect) (at C:/buildslave/unity/build/Editor/Mono/GUI/ReorderableList.cs:412)
ScrollableList.DoList (Single height)
uAdventure.Editor.ColumnList.DoList (Single height)
uAdventure.Editor.DataControlList.DoList (Single height)
uAdventure.Editor.CompletablesWindow.Draw (Int32 aID)
uAdventure.Editor.LayoutWindow.OnGUI ()
uAdventure.Editor.EditorWindowBase.OnGUI ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)
```
- Error 2:
```
GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

Creo que solamente son esos dos errores, porque se generaran como 6-7 errores por segundo y no alcanzo a distinguir si aparece alguno distinto, pero parece que solo son esos dos repetidos muchas veces.

Como observación, ya no aparece parte de la GUI, (además el error menciona la GUI, así que no creo que sea casualidad), no aparece ni lo de arriba de la lista, ni lo de abajo para poder añadir más variables.

Si necesitáis más información preguntad, esta vez no lo tocamos

**Comment by borjacano97** [comment]
El repositorio del proyecto:
https://github.com/alex97ortega/Usability

**Comment by Synpheros** [comment]
Hola @borjacano97,

Te agradezco tu reporte tan detallado. No obstante lamento decirte que el error fue corregido hace 2 versiones, en la versión: "uAdventure v0.10: Analytics update". Mirando las capturas que mandas puedo ver que tu editor no tiene la pestaña de "Tracker Config" que fue incluida en dicha versión.

Actualiza a la última versión y todo comenzará a funcionar.

**Comment by Synpheros** [comment]
Hola, Balta me ha dicho que habéis encontrado problemas de nuevo. Necesito que hagas 2 cosas por mi:
1- Confirma que, en la pestaña de analytics aparece la pestaña de "Tracker Config" si no aparece, volver a importar el paquete.
2- Busca el fichero chapter1.xml dentro de CurrentGame y subelo a la issue para que pueda ver en detalle.

**Comment by borjacano97** [comment]
1. Sí aparece, adjunto además captura porque se ve claramente qué parte de la GUI da problemas
![image](https://user-images.githubusercontent.com/19183801/54916317-8bc0c380-4ef9-11e9-8b28-cec5dd4ab9e7.png)
2. Te lo adjunto como .txt poque github no me permite subir un .xml
[chapter1.txt](https://github.com/e-ucm/uAdventure/files/3003009/chapter1.txt)

**Comment by Victorma** [comment]
El problema se debía a que se creó un completable sin asignar variable. Al guardar y tratar de restaurarlo generaba una variable null que rompía el editor.

La versión inmediata con el bug corregido estará disponible en: https://ci.appveyor.com/project/eucm/uadventure/builds/23338147/artifacts
