### ISSUE TITLE
Analytics no funciona correctamente

### ISSUE THREAD

**Issue by Adriana02** [e-ucm/uAdventure#62]
Al abrir la pestaña de Analytics, al elegir la opción "Completables" empiezan a salir muchísimos errores, y todos los completables que habíamos creado no están y aparece este dibujo:
![ErrorAnalytics](https://user-images.githubusercontent.com/18736013/54868864-7a5ca780-4d91-11e9-98ca-faad20760687.PNG)

Los errores que aparecen son estos 3 repetidos constantemente:
![ErrorAnalytics2](https://user-images.githubusercontent.com/18736013/54868870-8f393b00-4d91-11e9-808f-4fd9967b64cb.PNG)

Aclarar que el jueves nos funcionaba correctamente esta pestaña y no teníamos ningún problema al crear Completables.

**Comment by Synpheros** [comment]
Hola @Adriana02,

Estoy mirando los errores y es probable que uno de los completables se haya guardado en un estado corrupto. Si pudieras adjuntar el fichero chapter1.xml de tu proyecto me sería de gran ayuda para identificar el error.

**Comment by Adriana02** [comment]
Hola,

Al final hemos podido arreglar el problema reimportando otra vez el unity
package y en principio parece que funciona bien.

**Comment by Synpheros** [comment]
Bueno, si vuelve a haber algún otro problema comentarlo por aquí. De momento la dejo cerrada. Gracias!
