### ISSUE TITLE
Problema al configurar el layout en Linux

### ISSUE THREAD

**Issue by daviddavo** [e-ucm/uAdventure#66]
Usando Unity 2017.4.33f1 (Unity LTS) en Linux. Tras clickar en 'Configure Layout', se cierra y aparece esta ventana

![Sin nombre](https://user-images.githubusercontent.com/10263941/66573418-f1f9f480-eb72-11e9-8b55-52d99957ba3c.png)
Unity Hub permanece funcionando

**Comment by Victorma** [comment]
Hola @daviddavo, 

Puede ser porque el paquete que compartí accidentalmente no incluia la carpeta resources.

Prueba con el nuevo paquete v1.0.1b que acabo de subir: https://github.com/e-ucm/uAdventure/releases/download/v1.0.1/uAdventure_v1.0.1b.unitypackage

Me cuentas.

De todas formas en Linux tenemos un bug conocido por el cual no se muestran las imágenes de las escenas en edición. Salvo eso, el resto debería funcionar.

**Comment by daviddavo** [comment]
Con la versión nueva ha tardado mucho más en instalar (supongo que esta vez ha llegado a hacer la instalación completa), pero parece que cambia el layout bien

**Comment by Victorma** [comment]
Perfecto
