### ISSUE TITLE
Manual en PDF

### ISSUE THREAD

**Issue by daviddavo** [e-ucm/uAdventure#71]
Cuando lo abres en Word tarda mucho y parece que se desconfigura, además da algunos errores de configuración

Esto se solucionaría si se subiese el manual en .PDF

**Comment by Victorma** [comment]
El manual en PDF está disponible bajo el nombre de Users Guide.pdf junto al manual en word: https://github.com/e-ucm/uAdventure/releases/download/1.0/Users_Guide_v1.0.pdf
