### ISSUE TITLE
Múltiples acciones "Drag To" a diferentes objetos

### ISSUE THREAD

**Issue by onaranjoUCM** [e-ucm/uAdventure#79]
No parece existir la posibilidad de activar diferentes eventos al arrastrar un objeto a diferente otros objetos de la escena, ya que solo se activa el primer "Drag To" de la lista.

Ejemplo: Nuestro minijuego se basa en tirar diferentes tipos de basura a su contenedor apropiado y nos gustaría que al fallar se mostrara un mensaje y se restaran puntos, pero actualmente la "basura" solo puede interactuar con su contenedor correcto.

**Comment by Victorma** [comment]
No sabía que esto pasaba. Debe ser un error al filtrar las opciones. Gracias
