### ISSUE TITLE
Algunas ventanas de la interfaz no dan una visibilidad completa al abrirse

### ISSUE THREAD

**Issue by RamzaFFT** [e-ucm/uAdventure#80]
Hay algunas ventanas, como por ejemplo la de seleccionar slides para las cutscenes, que **al abrirse no muestran todas sus opciones**.

<img width="381" alt="Captura de pantalla 2019-10-24 a las 21 49 03" src="https://user-images.githubusercontent.com/22521856/67519933-2cea4500-f6a8-11e9-827b-cf92997e8db9.png">

En este caso, no se muestra la opción de aceptar los cambios. Al expandir la ventana, sí que aparece.

<img width="392" alt="Captura de pantalla 2019-10-24 a las 21 49 18" src="https://user-images.githubusercontent.com/22521856/67519962-383d7080-f6a8-11e9-8de6-bd4fe19a7adf.png">

Esto crea confusión a veces, puesto que en algunas ventanas, al añadir información y cerrarlas, se guarda lo que se ha creado, mientras que en otras (como la de este ejemplo) no.

**Grupo 1**

**Comment by Victorma** [comment]
Gracias por avisar de esto. Lo hemos visto alguna vez pero no sabíamos que seguía pasando. Me pongo
