### ISSUE TITLE
No deja hacer Build del proyecto

### ISSUE THREAD

**Issue by evivar** [e-ucm/uAdventure#82]
Cuando intentamos hacer Build project desde el menu de uAdventure salen dos errores diciendo:

Assets/uAdventure/Plugins/unity-tracker/csharp-tracker/TrackerAssetUnitTests/NUnitTests.cs(23,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?

Error building Player because scripts had compiler errors

**Comment by Victorma** [comment]
Oh, esto es un bug de la versión sin compilar (antiguamente lo distribuimos como dll). Borra el archivo y te dejará
