### ISSUE TITLE
Problemas al guardar

### ISSUE THREAD

**Issue by JuanBosque** [e-ucm/uAdventure#83]
A veces guardar no surte ningún efecto y al ejecutar el juego no te insta a guardar y los cambios realizados no tienen ningún efecto y se pierden

**Comment by Victorma** [comment]
Dime porfi los pasos para replicarlo o exáctamente el lugar donde no se te están guardando las cosas

**Comment by JuanBosque** [comment]
Cuando en los cambios que hacía no había añadido ni borrado ninguna escena al darle al play no me decía de guardar y se ejecutaba directamente ignorando los cambios que había hecho y al parar el juego ya no estaban los cambios que había hecho.

Intentar guardar el proyecto con File->Save Project tampoco hacía nada

**Comment by Victorma** [comment]
Interesante. Perdón por el retraso, pero necesitaba saber qué es lo que estás perdiendo justamente, porque si es todo es algo muy extraño, pero si son efectos o algo similar puede ser un bug que podría resolver

**Comment by JuanBosque** [comment]
Ahora mismo no recuerdo exactamente qué era pero creo que sólo estaba
cambiando los efectos que tenía clicar en un item en cuanto a las flags que
activaba/desactivaba y/o las condiciones también en cuanto a
flags/variables para la apariencia de un par de items

**Comment by Victorma** [comment]
Merged to #21
