### ISSUE TITLE
No se pueden borrar líneas de conversación restantes de un mismo nodo

### ISSUE THREAD

**Issue by RamzaFFT** [e-ucm/uAdventure#85]
En las conversaciones, al crear varias líneas de conversación en un mismo nodo, no se pueden borrar más adelante. Aunque aparece la opción (X) al lado de crear una nueva línea, no permite borrar las anteriores.

<img width="437" alt="Captura de pantalla 2019-10-29 a las 10 27 54" src="https://user-images.githubusercontent.com/22521856/67754730-3e7c7580-fa37-11e9-868b-dc3b85ce9227.png">

Esto puede ser molesto, ya que obliga a eliminar el nodo entero y volver a crearlo.

**Comment by Victorma** [comment]
Sí se puede, pero tienes que seleccinarlas primero desde el handle de la izquierda. Si esto no es suficientemente claro, qué idea crees que podría mejorarlo?

**Comment by Victorma** [comment]
He mejorado esto haciendo que cualquier click en la linea la haga focus. Si te sigue sin funcionar reabreme la issue
