### ISSUE TITLE
Fallo de textura con "Grab" y "Speak".

### ISSUE THREAD

**Issue by onaranjoUCM** [e-ucm/uAdventure#97]
Si tras coger un objeto (Acción Grab) se ejecuta una acción "Speak character" o "Speak player", se provoca que la textura del personaje falle y el bocadillo del texto no desaparezca.

Hacer la acción "Speak character" o "Speak player" antes de las acciones "remove element" y "generate object" evita el error.

Por si puede tener algo que ver, el objeto en cuestión está en una escena de mapa geoposicionado.

**Comment by Victorma** [comment]
Súbeme el proyecto porfis

**Comment by Victorma** [comment]
Espera, entiendo que es este proyecto: https://github.com/alejru08/uAdventure-BotanicaGeo
Asegúrame que está actualizado y le echo un vistazo

**Comment by onaranjoUCM** [comment]
Está recién subido, aunque de detectado que hay errores de texturas desde antes así que puede que uno provoque el otro.
